# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LYAutoPhotoPickers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LYAutoPhotoPickers
  pod 'JXPhotoBrowser'
  pod 'TOCropViewController'
  pod 'LYAutoUtils'

end
