# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'LYAutoPhotoPickers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LYAutoPhotoPickers
  pod 'LYAutoUtils'
  pod 'JXPhotoBrowser'
  pod 'CropViewController'
  
end
